name: "Lewis & Clark Hacker Club"
markdown: kramdown
highlighter: rouge
description: "The team behind Hack Night and the LC Startup Competition"
url: "http://lchack.org"
exclude: [compass.rb, config.ru, Gemfile, Gemfile.lock, Procfile, Rakefile, README.md, sass, unicorn.rb, vendor]
