name: "Lewis & Clark Hacker Club"
markdown: redcarpet
highlighter: pygments
description: "A student club at Lewis & Clark College focusing on cybersecurity and systems penetration."
url: "http://lchack.org"
